apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  type: NodePort
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 55001
      targetPort: 80
      nodePort: {{ .Values.argNodePort }}
